import "./globals.css";
import { Inter } from "next/font/google";
import { draftMode } from "next/headers";
import { Providers } from "./providers";
import { getAllMappedAudiences, getAllMappedExperiences } from "../lib/client";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({ children }) => {
  // TODO: How can we pass Draft Mode down to all components instead of having to check in multiple levels?
  // TODO: Maybe `useContext` or custom React hooks like Aubrie did with her "global context" stuff?
  const { isEnabled } = draftMode();

  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center justify-between p-12 md:p-24">
          <div className="z-10 w-full max-w-5xl items-center justify-between text-sm lg:flex flex-col">
            <Providers
              draftModeEnabled={isEnabled}
              audiences={(await getAllMappedAudiences()) || []}
              experiences={(await getAllMappedExperiences()) || []}
            >
              {children}
            </Providers>
          </div>
        </main>
      </body>
    </html>
  );
};

export default RootLayout;
